version: '3.8'

services:
  # 1. Ma'lumotlar bazasi (PostgreSQL)
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: jobify-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=jobify
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobify"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    container_name: jobify-redis
    ports:
      - "6379:6379"

  # 3. Asosiy Backend (FastAPI)
  web:
    build: .
    platform: linux/amd64
    container_name: jobify-web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # 4. Celery Worker
  worker:
    build: .
    platform: linux/amd64
    container_name: jobify-worker
    command: celery -A app.core.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data: